/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alexordonez_lab5.alexycruz_examen;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex Ordonez
 */
public class menu extends javax.swing.JFrame {
//usuario kim en el final

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        j_id_famm = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        j_contra_famm = new javax.swing.JTextField();
        j_nom_famm = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        j_trab_famm = new javax.swing.JTextField();
        j_rol_famm = new javax.swing.JComboBox<>();
        j_alt_famm = new javax.swing.JTextField();
        j_peso_famm = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        radiosexo_famm = new javax.swing.JRadioButton();
        radiosex_famm = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        j_eda_famm = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        j_est_famm = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        j_fam_mod = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        j_id_perm = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        j_contra_perm = new javax.swing.JTextField();
        j_nom_perm = new javax.swing.JTextField();
        j_ocp_perm = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        radiosexo_perm = new javax.swing.JRadioButton();
        radiosex_perm = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        j_eda_perm = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        j_hor_perm = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        j_sue_perm = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        j_est_perm = new javax.swing.JTextField();
        j_per_mod = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        j_persona = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        j_mensajes = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        j_recibidos = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        j_list = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        agregar = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        j_id_fama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        j_nom_fama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        j_trab_fama = new javax.swing.JTextField();
        j_rol_fama = new javax.swing.JComboBox<>();
        j_alt_fama = new javax.swing.JTextField();
        j_peso_fama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        radiosexo_fama = new javax.swing.JRadioButton();
        radiosex_fama = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        j_eda_fama = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        j_est_fama = new javax.swing.JTextField();
        j_contra_fama = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        j_id_pera = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        j_contra_pera = new javax.swing.JTextField();
        j_nom_pera = new javax.swing.JTextField();
        j_ocp_pera = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        radiosexo_pera = new javax.swing.JRadioButton();
        radiosex_pera = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        j_eda_pera = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        j_hor_pera = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        j_sue_pera = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        j_est_pera = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        j_dueno = new javax.swing.JComboBox<>();
        j_mar_oba = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        j_des_oba = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        j_tam_oba = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        j_cal_oba = new javax.swing.JTextField();
        j_tipo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        j_el_persona = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        j_el_objeto = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        per_actual = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b_ingresar = new javax.swing.JButton();
        jp_pass = new javax.swing.JPasswordField();

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_id_famm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_id_fammActionPerformed(evt);
            }
        });
        jPanel5.add(j_id_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 44, 91, -1));

        jLabel27.setText("Id");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 47, -1, -1));

        jLabel28.setText("contrasena");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 99, -1, -1));

        jLabel29.setText("nombre");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 159, -1, -1));

        jLabel30.setText("Trabajo");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel31.setText("rol");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        j_contra_famm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_contra_fammActionPerformed(evt);
            }
        });
        jPanel5.add(j_contra_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 96, 87, -1));
        jPanel5.add(j_nom_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 156, 87, -1));

        jLabel33.setText("altura cm");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 47, -1, -1));

        jLabel34.setText("peso lbs");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 99, -1, -1));

        j_trab_famm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_trab_fammActionPerformed(evt);
            }
        });
        jPanel5.add(j_trab_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 87, -1));

        j_rol_famm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre", "Padre", "Hermano", "Hermana", "Esposo" }));
        jPanel5.add(j_rol_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        jPanel5.add(j_alt_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 44, 83, -1));
        jPanel5.add(j_peso_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 96, 84, -1));

        jButton3.setText("Modificar");
        jButton3.setEnabled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 142, 56));

        jLabel35.setText("sexo");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 151, -1, -1));

        buttonGroup1.add(radiosexo_famm);
        radiosexo_famm.setText("M");
        jPanel5.add(radiosexo_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 147, -1, -1));

        buttonGroup1.add(radiosex_famm);
        radiosex_famm.setText("F");
        jPanel5.add(radiosex_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 147, -1, -1));

        jLabel36.setText("edad");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        jPanel5.add(j_eda_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 84, -1));

        jLabel37.setText("estado civil");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));
        jPanel5.add(j_est_famm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 84, -1));

        jLabel51.setText("persona");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 16, -1, -1));

        j_fam_mod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                j_fam_modItemStateChanged(evt);
            }
        });
        j_fam_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_fam_modActionPerformed(evt);
            }
        });
        jPanel5.add(j_fam_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 13, 91, -1));

        jTabbedPane2.addTab("familiar", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_id_perm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_id_permActionPerformed(evt);
            }
        });
        jPanel6.add(j_id_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 58, 91, -1));

        jLabel38.setText("Id");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 61, -1, -1));

        jLabel39.setText("contrasena");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 98, -1, -1));

        jLabel40.setText("nombre");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 148, -1, -1));

        jLabel41.setText("Ocupacion");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 194, -1, -1));

        j_contra_perm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_contra_permActionPerformed(evt);
            }
        });
        jPanel6.add(j_contra_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 98, 87, -1));
        jPanel6.add(j_nom_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 148, 87, -1));

        j_ocp_perm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_ocp_permActionPerformed(evt);
            }
        });
        jPanel6.add(j_ocp_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 191, 87, -1));

        jButton4.setText("Modificar");
        jButton4.setEnabled(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 290, 142, 56));

        jLabel45.setText("sexo");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 72, -1, -1));

        buttonGroup2.add(radiosexo_perm);
        radiosexo_perm.setText("M");
        jPanel6.add(radiosexo_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 68, -1, -1));

        buttonGroup2.add(radiosex_perm);
        radiosex_perm.setText("F");
        jPanel6.add(radiosex_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 68, -1, -1));

        jLabel46.setText("edad");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        j_eda_perm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_eda_permActionPerformed(evt);
            }
        });
        jPanel6.add(j_eda_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 84, -1));

        jLabel47.setText("horario");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 246, -1, -1));
        jPanel6.add(j_hor_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 243, 87, -1));

        jLabel48.setText("sueldo");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 111, -1, -1));

        j_sue_perm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_sue_permActionPerformed(evt);
            }
        });
        jPanel6.add(j_sue_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 84, -1));

        jLabel49.setText("estado civil");
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
        jPanel6.add(j_est_perm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 84, -1));

        j_per_mod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                j_per_modItemStateChanged(evt);
            }
        });
        j_per_mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_per_modMouseClicked(evt);
            }
        });
        jPanel6.add(j_per_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 13, 107, -1));

        jLabel50.setText("persona");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 16, -1, -1));

        jTabbedPane2.addTab("personal", jPanel6);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Objeto", jPanel12);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        jLabel52.setText("persona");

        jLabel53.setText("Mensaje");

        j_mensajes.setColumns(20);
        j_mensajes.setRows(5);
        jScrollPane1.setViewportView(j_mensajes);

        jButton5.setText("Enviar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        j_recibidos.setColumns(20);
        j_recibidos.setRows(5);
        jScrollPane3.setViewportView(j_recibidos);

        jLabel9.setText("Recibidos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(203, 203, 203))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addComponent(j_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel53)))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Mensajeria", jPanel4);

        j_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "ID", "Trabajo", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_list, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(j_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jTabbedPane1.addTab("Listar", jPanel7);

        j_id_fama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_id_famaActionPerformed(evt);
            }
        });

        jLabel4.setText("Id");

        jLabel5.setText("contrasena");

        jLabel6.setText("nombre");

        jLabel7.setText("Trabajo");

        jLabel8.setText("rol");

        jLabel10.setText("altura cm");

        jLabel11.setText("peso lbs");

        j_trab_fama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_trab_famaActionPerformed(evt);
            }
        });

        j_rol_fama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre", "Padre", "Hermano", "Hermana", "Esposo" }));

        jButton1.setText("Agregar");
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setText("sexo");

        buttonGroup1.add(radiosexo_fama);
        radiosexo_fama.setText("M");

        buttonGroup1.add(radiosex_fama);
        radiosex_fama.setText("F");

        jLabel21.setText("edad");

        jLabel26.setText("estado civil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(36, 36, 36)
                        .addComponent(j_trab_fama, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel26)
                        .addGap(28, 28, 28)
                        .addComponent(j_est_fama, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel4)
                                        .addGap(53, 53, 53)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j_id_fama, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j_nom_fama, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j_rol_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j_contra_fama, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(j_peso_fama))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(j_alt_fama, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(radiosexo_fama)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radiosex_fama))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel21)
                                .addGap(45, 45, 45)
                                .addComponent(j_eda_fama, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(j_alt_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_id_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(j_peso_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_contra_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(j_nom_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(radiosexo_fama)
                                    .addComponent(radiosex_fama))
                                .addGap(6, 6, 6)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(j_trab_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(j_est_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(j_rol_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_eda_fama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jTabbedPane3.addTab("Agregar familiar", jPanel1);

        j_id_pera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_id_peraActionPerformed(evt);
            }
        });

        jLabel12.setText("Id");

        jLabel13.setText("contrasena");

        jLabel14.setText("nombre");

        jLabel15.setText("Ocupacion");

        j_contra_pera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_contra_peraActionPerformed(evt);
            }
        });

        j_ocp_pera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_ocp_peraActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.setEnabled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel20.setText("sexo");

        buttonGroup2.add(radiosexo_pera);
        radiosexo_pera.setText("M");

        buttonGroup2.add(radiosex_pera);
        radiosex_pera.setText("F");

        jLabel22.setText("edad");

        j_eda_pera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_eda_peraActionPerformed(evt);
            }
        });

        jLabel23.setText("horario");

        jLabel24.setText("sueldo");

        j_sue_pera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_sue_peraActionPerformed(evt);
            }
        });

        jLabel25.setText("estado civil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel23))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j_hor_pera, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j_id_pera, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(j_nom_pera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addComponent(j_contra_pera, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(j_ocp_pera, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j_sue_pera, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(radiosexo_pera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radiosex_pera))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(j_eda_pera, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j_est_pera, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_id_pera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20)
                    .addComponent(radiosexo_pera)
                    .addComponent(radiosex_pera))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(j_contra_pera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(j_sue_pera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(j_nom_pera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_ocp_pera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel25)
                            .addComponent(j_est_pera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(j_eda_pera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(j_hor_pera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane3.addTab("Agregar personal", jPanel2);

        jLabel17.setText("Marca");

        jLabel18.setText("Descripcion");

        j_dueno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        j_des_oba.setColumns(20);
        j_des_oba.setRows(5);
        jScrollPane4.setViewportView(j_des_oba);

        jLabel42.setText("calidad");

        jLabel44.setText("tamano");

        jButton8.setText("Agregar");
        jButton8.setEnabled(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        j_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setText("Color");

        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(25, 25, 25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_cal_oba, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_mar_oba, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel42))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j_dueno, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addGap(33, 33, 33)
                                .addComponent(j_tam_oba, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(j_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(77, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(j_dueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_mar_oba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(j_tam_oba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(j_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(j_cal_oba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Objeto", jPanel8);

        javax.swing.GroupLayout agregarLayout = new javax.swing.GroupLayout(agregar);
        agregar.setLayout(agregarLayout);
        agregarLayout.setHorizontalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        agregarLayout.setVerticalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar", agregar);

        j_el_persona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton7.setText("Eliminar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(j_el_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(j_el_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Eliminar Persona", jPanel10);

        j_el_objeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton6.setText("Eliminar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(j_el_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(j_el_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Eliminar Objeto", jPanel11);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("eliminar", jPanel9);

        per_actual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        per_actual.setText("Persona");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu.getContentPane());
        menu.getContentPane().setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(per_actual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addComponent(per_actual, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Log in ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID");

        jt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Contrasena");

        b_ingresar.setText("Ingresar");
        b_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_ingresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jp_pass))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(b_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_idActionPerformed

    private void b_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ingresarMouseClicked
        if (flag == 1) {
            personas.add(kim);
            familiares.add(kim);
            flag++;
        }
        for (Persona p : personas) {
            if (p.getID() == Integer.parseInt(jt_id.getText()) && p.getContrasena().equals(jp_pass.getText())) {
                this.dispose();
                per_actual.setText(p.getNombre());
                actual = p;
                if(p.equals(kim)){
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);
                    jButton3.setEnabled(true);
                    jButton4.setEnabled(true);
                    jButton8.setEnabled(true);
                }
                menu.setVisible(true);
            }
        }
        String h = "";
        for (String t : actual.getMensajes()) {
            h += t+"\n";
        }
        j_recibidos.setText(h);
    }//GEN-LAST:event_b_ingresarMouseClicked

    private void j_id_famaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_id_famaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_id_famaActionPerformed

    private void j_trab_famaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_trab_famaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_trab_famaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j_id_fammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_id_fammActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_id_fammActionPerformed

    private void j_contra_fammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_contra_fammActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_contra_fammActionPerformed

    private void j_trab_fammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_trab_fammActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_trab_fammActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void j_id_permActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_id_permActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_id_permActionPerformed

    private void j_contra_permActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_contra_permActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_contra_permActionPerformed

    private void j_ocp_permActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_ocp_permActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_ocp_permActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void j_eda_permActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_eda_permActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_eda_permActionPerformed

    private void j_sue_permActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_sue_permActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_sue_permActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre = j_nom_fama.getText();
        int id = Integer.parseInt(j_id_fama.getText());
        String contra = j_contra_fama.getText();
        if (id(id)) {
            String estado = j_est_fama.getText();
            int edad = Integer.parseInt(j_eda_fama.getText());
            String sexo = "";
            String trabajo = j_trab_fama.getText();
            int alt = Integer.parseInt(j_alt_fama.getText());
            int peso = Integer.parseInt(j_peso_fama.getText());
            if (radiosexo_fama.isSelected()) {
                sexo = "M";
            } else {
                sexo = "F";
            }
            String rol = "";
            if (j_rol_fama.getSelectedItem().equals("Hermana")) {
                int o = 0;
                for (familiar p : familiares) {
                    if (p.getRol().equals("Hermana")) {
                        o++;
                    }
                }
                if (o == 4) {
                    JOptionPane.showMessageDialog(this, "No se pudo agregar");
                } else {
                    rol = ((String) j_rol_fama.getSelectedItem());
                    Persona x = new familiar(trabajo, peso, alt, rol, nombre, sexo, estado, contra, id, edad);
                    personas.add(x);
                    familiares.add((familiar) x);
                    DefaultComboBoxModel modelo = (DefaultComboBoxModel) j_fam_mod.getModel();
                    modelo.addElement(x);
                    j_fam_mod.setModel(modelo);
                    DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) j_persona.getModel();
                    modelo2.addElement(x);
                    j_persona.setModel(modelo2);
                }
            } else {
                boolean u = false;
                for (familiar p : familiares) {
                    if (j_rol_fama.getSelectedItem().equals(p.getRol())) {
                        u = true;
                    }
                }
                if (u == true) {
                    JOptionPane.showMessageDialog(this, "No se pudo agregar");
                } else {
                    rol = ((String) j_rol_fama.getSelectedItem());
                    Persona x = new familiar(trabajo, peso, alt, rol, nombre, sexo, estado, contra, id, edad);
                    personas.add(x);
                    familiares.add((familiar) x);
                    DefaultComboBoxModel modelo = (DefaultComboBoxModel) j_fam_mod.getModel();
                    modelo.addElement(x);
                    j_fam_mod.setModel(modelo);
                    DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) j_persona.getModel();
                    modelo2.addElement(x);
                    j_persona.setModel(modelo2);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void j_fam_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_fam_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_fam_modActionPerformed

    private void j_sue_peraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_sue_peraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_sue_peraActionPerformed

    private void j_eda_peraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_eda_peraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_eda_peraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void j_ocp_peraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_ocp_peraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_ocp_peraActionPerformed

    private void j_contra_peraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_contra_peraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_contra_peraActionPerformed

    private void j_id_peraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_id_peraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_id_peraActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nombre = j_nom_pera.getText();
        int id = Integer.parseInt(j_id_pera.getText());
        String contra = j_contra_pera.getText();
        if (id(id)) {
            String estado = j_est_pera.getText();
            int edad = Integer.parseInt(j_eda_pera.getText());
            String sexo;
            String ocupa = j_ocp_pera.getText();
            String horario = j_hor_pera.getText();
            double sueldo = Double.parseDouble(j_sue_pera.getText());
            if (radiosexo_pera.isSelected()) {
                sexo = "M";
            } else {
                sexo = "F";
            }
            Persona x = new personal(ocupa, horario, 0, sueldo, nombre, sexo, estado, contra, id, edad);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) j_per_mod.getModel();
            modelo.addElement(x);
            personas.add(x);
            empleados.add((personal) x);
            j_per_mod.setModel(modelo);
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) j_persona.getModel();
            modelo2.addElement(x);
            j_persona.setModel(modelo2);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar");
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void j_fam_modItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_j_fam_modItemStateChanged
        if (evt.getStateChange() >= 2) {
            familiar x = ((familiar) j_fam_mod.getSelectedItem());
            j_id_famm.setText("" + x.getID());
            j_contra_famm.setText(x.getContrasena());
            j_nom_famm.setText(x.getNombre());
            j_est_famm.setText(x.getEstado_c());
            if (x.getSexo().equals("M")) {
                radiosexo_famm.setSelected(true);
            } else {
                radiosex_famm.setSelected(true);
            }

            j_rol_famm.setSelectedItem(x.getRol());
            j_trab_famm.setText(x.getTrabajo());
            j_alt_famm.setText("" + x.getAltura());
            j_peso_famm.setText("" + x.getPeso());
        }
    }//GEN-LAST:event_j_fam_modItemStateChanged

    private void j_per_modMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_per_modMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_j_per_modMouseClicked

    private void j_per_modItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_j_per_modItemStateChanged
        if (evt.getStateChange() >= 2) {
            personal x = ((personal) j_per_mod.getSelectedItem());
            j_id_perm.setText("" + x.getID());
            j_contra_perm.setText(x.getContrasena());
            j_nom_perm.setText(x.getNombre());
            j_est_perm.setText(x.getEstado_c());
            if (x.getSexo().equals("M")) {
                radiosexo_perm.setSelected(true);
            } else {
                radiosex_perm.setSelected(true);
            }
            j_ocp_perm.setText(x.getOcupacion());
            j_sue_perm.setText("" + x.getSueldo());
            j_hor_perm.setText(x.getHorario());
        }
    }//GEN-LAST:event_j_per_modItemStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String nombre = j_nom_famm.getText();
        int id = Integer.parseInt(j_id_famm.getText());
        String contra = j_contra_famm.getText();
        if (id(id)) {
            String estado = j_est_famm.getText();
            int edad = Integer.parseInt(j_eda_famm.getText());
            String sexo = "";
            String trabajo = j_trab_famm.getText();
            int alt = Integer.parseInt(j_alt_famm.getText());
            int peso = Integer.parseInt(j_peso_famm.getText());
            if (radiosexo_famm.isSelected()) {
                sexo = "M";
            } else {
                sexo = "F";
            }
            String rol = "";
            if (j_rol_famm.getSelectedItem().equals("Hermana")) {
                int o = 0;
                for (familiar p : familiares) {
                    if (p.getRol().equals("Hermana")) {
                        o++;
                    }
                }
                if (o == 4) {
                    JOptionPane.showMessageDialog(this, "No se pudo modificar");
                } else {
                    rol = ((String) j_rol_famm.getSelectedItem());
                    familiar x = ((familiar) j_fam_mod.getSelectedItem());
                    x.setContrasena(contra);
                    x.setEstado_c(estado);
                    x.setID(id);
                    x.setNombre(nombre);
                    x.setSexo(sexo);
                    x.setAltura(alt);
                    x.setPeso(peso);
                    x.setRol(rol);
                    x.setTrabajo(trabajo);
                    DefaultComboBoxModel modelo = (DefaultComboBoxModel) j_fam_mod.getModel();
                    j_fam_mod.setModel(modelo);
                }
            } else {
                boolean u = false;
                for (familiar p : familiares) {
                    if (j_rol_famm.getSelectedItem().equals(p.getRol())) {
                        u = true;
                    }
                }
                if (u == true) {
                    JOptionPane.showMessageDialog(this, "No se pudo agregar");
                } else {
                    rol = ((String) j_rol_famm.getSelectedItem());
                    familiar x = ((familiar) j_rol_famm.getSelectedItem());
                    x.setContrasena(contra);
                    x.setEstado_c(estado);
                    x.setID(id);
                    x.setNombre(nombre);
                    x.setSexo(sexo);
                    x.setAltura(alt);
                    x.setPeso(peso);
                    x.setRol(rol);
                    x.setTrabajo(trabajo);
                    DefaultComboBoxModel modelo = (DefaultComboBoxModel) j_fam_mod.getModel();
                    j_fam_mod.setModel(modelo);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo modificar");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String nombre = j_nom_pera.getText();
        int id = Integer.parseInt(j_id_pera.getText());
        String contra = j_contra_pera.getText();
        if (id(id)) {
            String estado = j_est_pera.getText();
            int edad = Integer.parseInt(j_eda_pera.getText());
            String sexo;
            String ocupa = j_ocp_pera.getText();
            String horario = j_hor_pera.getText();
            double sueldo = Double.parseDouble(j_sue_pera.getText());
            if (radiosexo_pera.isSelected()) {
                sexo = "M";
            } else {
                sexo = "F";
            }
            personal x = (personal) j_per_mod.getSelectedItem();
            x.setContrasena(contra);
            x.setEstado_c(estado);
            x.setHorario(horario);
            x.setID(id);
            x.setNombre(nombre);
            x.setOcupacion(ocupa);
            x.setSexo(sexo);
            x.setSueldo(sueldo);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) j_per_mod.getModel();
            j_per_mod.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if ((((familiar) actual).getRol().equals("admi") || ((familiar) actual).getRol().equals("Esposo")) && (((familiar) j_persona.getSelectedItem()).getRol().equals("admi") || ((familiar) j_persona.getSelectedItem()).getRol().equals("Esposo"))) {
            String m = j_mensajes.getText();
            String h = "Hola:\n";
            for (int i = 0; i < m.length(); i++) {
                char e = m.charAt(i);
                e = (char) (m.codePointAt(i) + 3);
                h += e;
            }
            JOptionPane.showMessageDialog(this, "palabra ABC");
            String s="";
            for (int i = 0; i <h.length(); i++) {
                for (int j = 0; j < 3; j++) {
                    if(j*i<h.length()){
                        s+=h.charAt(j*i);
                    }
                }
            }
            for (int i = 0; i <h.length(); i++) {
                for (int j = 0; j < 3; j++) {
                    if(j*i+1<h.length()){
                        s+=h.charAt(j*i+1);
                    }
                }
            }
            for (int i = 0; i <h.length(); i++) {
                for (int j = 0; j < 3; j++) {
                    if(j*i+2<h.length()){
                        s+=h.charAt(j*i+2);
                    }
                }
            }
            s=s.toUpperCase();
            char p[][]=matriz();
            JOptionPane.showMessageDialog(null, "palabra clave ABC");
            int fil;
            int col;
            String l="";
            String o="ABC";
            int r=0;
            for (int j = 0; j < s.length(); j++) {
                r++;
                for (int i = 0; i < 26; i++) {
                    if(s.charAt(j)==p[0][i]){
                        col=i;
                        l+=p[r][i];
                    }
                }
                if(r==3){
                    r=0;
                }
            }
            ((Persona)j_persona.getSelectedItem()).getMensajes().add(l);
        }else{
            ((Persona) j_persona.getSelectedItem()).getMensajes().add("Mensaje de: "
                    + actual.getNombre() + "\n" + j_mensajes.getText());
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        String marca=j_mar_oba.getText();
        String desc=j_des_oba.getText();
        int tamano=Integer.parseInt(j_tam_oba.getText());
        int cal=Integer.parseInt(j_cal_oba.getText());
        familiar y=((familiar)j_dueno.getSelectedItem());
        Color c=jButton9.getBackground();
        String o=(String)j_tipo.getSelectedItem();
        if(j_tipo.getSelectedItem().equals("zapato")){
            int talla=Integer.parseInt(JOptionPane.showInputDialog("Ingrese la talla"));
            String material_suela=JOptionPane.showInputDialog("Ingrese el material de la suela");
            int confort=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el confort"));
            objetos.add(new zapato( talla, confort, material_suela, c, desc, marca, tamano, cal,  y));
        }
        
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        jButton9.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_jButton9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregar;
    private javax.swing.JButton b_ingresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField j_alt_fama;
    private javax.swing.JTextField j_alt_famm;
    private javax.swing.JTextField j_cal_oba;
    private javax.swing.JPasswordField j_contra_fama;
    private javax.swing.JTextField j_contra_famm;
    private javax.swing.JTextField j_contra_pera;
    private javax.swing.JTextField j_contra_perm;
    private javax.swing.JTextArea j_des_oba;
    private javax.swing.JComboBox<String> j_dueno;
    private javax.swing.JTextField j_eda_fama;
    private javax.swing.JTextField j_eda_famm;
    private javax.swing.JTextField j_eda_pera;
    private javax.swing.JTextField j_eda_perm;
    private javax.swing.JComboBox<String> j_el_objeto;
    private javax.swing.JComboBox<String> j_el_persona;
    private javax.swing.JTextField j_est_fama;
    private javax.swing.JTextField j_est_famm;
    private javax.swing.JTextField j_est_pera;
    private javax.swing.JTextField j_est_perm;
    private javax.swing.JComboBox<String> j_fam_mod;
    private javax.swing.JTextField j_hor_pera;
    private javax.swing.JTextField j_hor_perm;
    private javax.swing.JTextField j_id_fama;
    private javax.swing.JTextField j_id_famm;
    private javax.swing.JTextField j_id_pera;
    private javax.swing.JTextField j_id_perm;
    private javax.swing.JComboBox<String> j_list;
    private javax.swing.JTextField j_mar_oba;
    private javax.swing.JTextArea j_mensajes;
    private javax.swing.JTextField j_nom_fama;
    private javax.swing.JTextField j_nom_famm;
    private javax.swing.JTextField j_nom_pera;
    private javax.swing.JTextField j_nom_perm;
    private javax.swing.JTextField j_ocp_pera;
    private javax.swing.JTextField j_ocp_perm;
    private javax.swing.JComboBox<String> j_per_mod;
    private javax.swing.JComboBox<String> j_persona;
    private javax.swing.JTextField j_peso_fama;
    private javax.swing.JTextField j_peso_famm;
    private javax.swing.JTextArea j_recibidos;
    private javax.swing.JComboBox<String> j_rol_fama;
    private javax.swing.JComboBox<String> j_rol_famm;
    private javax.swing.JTextField j_sue_pera;
    private javax.swing.JTextField j_sue_perm;
    private javax.swing.JTextField j_tam_oba;
    private javax.swing.JComboBox<String> j_tipo;
    private javax.swing.JTextField j_trab_fama;
    private javax.swing.JTextField j_trab_famm;
    private javax.swing.JPasswordField jp_pass;
    private javax.swing.JTextField jt_id;
    private javax.swing.JFrame menu;
    private javax.swing.JLabel per_actual;
    private javax.swing.JRadioButton radiosex_fama;
    private javax.swing.JRadioButton radiosex_famm;
    private javax.swing.JRadioButton radiosex_pera;
    private javax.swing.JRadioButton radiosex_perm;
    private javax.swing.JRadioButton radiosexo_fama;
    private javax.swing.JRadioButton radiosexo_famm;
    private javax.swing.JRadioButton radiosexo_pera;
    private javax.swing.JRadioButton radiosexo_perm;
    // End of variables declaration//GEN-END:variables

    //Variables Creadas
    familiar kim = new familiar("actriz", 130, 180, "admi", "kim", "F", "Casada", "kardashian", 123456, 24);
    Persona actual;
    ArrayList<Persona> personas = new ArrayList();
    ArrayList<familiar> familiares = new ArrayList();
    ArrayList<personal> empleados = new ArrayList();
    ArrayList<Objeto> objetos=new ArrayList();
    int flag;

    public boolean id(int g) {
        boolean l = true;
        for (Persona p : personas) {
            if (p.getID() == g) {
                l = false;
            }
        }
        return l;
    }
    public char[][] matriz(){
        char [][]h={{'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'},
                    {'B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A'},
                    {'C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B'},
                    {'D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C'},
                    {'E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D'},
                    {'F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E'},
                    {'G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F'},
                    {'H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G'}
            ,       {'I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H'},
                    {'J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I'},
                    {'K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J'}
            ,       {'L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K'},
                    {'M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L'},
                    {'N','O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M'},
                    {'O','P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N'},
                    {'P','Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O'},
                    {'Q','R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P'},
                    {'R','S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q'},
                    {'S','T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R'},
                    {'T','U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S'},
                    {'U','V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T'},
                    {'V','W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U'},
                    {'W','X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V'},
                    {'X','Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W'},
                    {'Y','Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X'},
                    {'Z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y'}};
        return h;
    }
}
